// This file will be auto-generated by: npx supabase gen types typescript
// For now, we use the manually defined types from ./index.ts
// After connecting to Supabase and running migrations, regenerate with:
// npx supabase gen types typescript --local > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      buildings: {
        Row: {
          id: string;
          name: string;
          address: string | null;
          total_units: number | null;
          bank_account_info: Json | null;
          payment_deadline_hours: number;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          address?: string | null;
          total_units?: number | null;
          bank_account_info?: Json | null;
          payment_deadline_hours?: number;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string | null;
          total_units?: number | null;
          bank_account_info?: Json | null;
          payment_deadline_hours?: number;
          timezone?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          building_id: string;
          role: string;
          full_name: string;
          email: string;
          phone: string | null;
          national_id: string | null;
          emergency_contact: Json | null;
          avatar_url: string | null;
          preferred_locale: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          building_id: string;
          role: string;
          full_name: string;
          email: string;
          phone?: string | null;
          national_id?: string | null;
          emergency_contact?: Json | null;
          avatar_url?: string | null;
          preferred_locale?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          building_id?: string;
          role?: string;
          full_name?: string;
          email?: string;
          phone?: string | null;
          national_id?: string | null;
          emergency_contact?: Json | null;
          avatar_url?: string | null;
          preferred_locale?: string;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      apartments: {
        Row: {
          id: string;
          building_id: string;
          unit_number: string;
          floor: number | null;
          area_sqm: number | null;
          bedrooms: number | null;
          bathrooms: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          building_id: string;
          unit_number: string;
          floor?: number | null;
          area_sqm?: number | null;
          bedrooms?: number | null;
          bathrooms?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          building_id?: string;
          unit_number?: string;
          floor?: number | null;
          area_sqm?: number | null;
          bedrooms?: number | null;
          bathrooms?: number | null;
          status?: string;
          updated_at?: string;
        };
      };
      apartment_owners: {
        Row: {
          id: string;
          apartment_id: string;
          profile_id: string;
          is_primary: boolean;
          move_in_date: string | null;
          move_out_date: string | null;
        };
        Insert: {
          id?: string;
          apartment_id: string;
          profile_id: string;
          is_primary?: boolean;
          move_in_date?: string | null;
          move_out_date?: string | null;
        };
        Update: {
          apartment_id?: string;
          profile_id?: string;
          is_primary?: boolean;
          move_in_date?: string | null;
          move_out_date?: string | null;
        };
      };
      public_spaces: {
        Row: {
          id: string;
          building_id: string;
          name: string;
          description: string | null;
          capacity: number | null;
          photos: string[];
          hourly_rate: number;
          deposit_amount: number;
          requires_approval: boolean;
          min_advance_hours: number;
          max_advance_days: number;
          max_duration_hours: number;
          max_monthly_per_owner: number;
          gap_minutes: number;
          quiet_hours_start: string | null;
          quiet_hours_end: string | null;
          cancellation_hours: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          building_id: string;
          name: string;
          description?: string | null;
          capacity?: number | null;
          photos?: string[];
          hourly_rate?: number;
          deposit_amount?: number;
          requires_approval?: boolean;
          min_advance_hours?: number;
          max_advance_days?: number;
          max_duration_hours?: number;
          max_monthly_per_owner?: number;
          gap_minutes?: number;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          cancellation_hours?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          building_id?: string;
          name?: string;
          description?: string | null;
          capacity?: number | null;
          photos?: string[];
          hourly_rate?: number;
          deposit_amount?: number;
          requires_approval?: boolean;
          min_advance_hours?: number;
          max_advance_days?: number;
          max_duration_hours?: number;
          max_monthly_per_owner?: number;
          gap_minutes?: number;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          cancellation_hours?: number;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      availability_schedules: {
        Row: {
          id: string;
          space_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
        };
        Insert: {
          id?: string;
          space_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
        };
        Update: {
          space_id?: string;
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
        };
      };
      blackout_dates: {
        Row: {
          id: string;
          space_id: string;
          date: string;
          reason: string | null;
        };
        Insert: {
          id?: string;
          space_id: string;
          date: string;
          reason?: string | null;
        };
        Update: {
          space_id?: string;
          date?: string;
          reason?: string | null;
        };
      };
      reservations: {
        Row: {
          id: string;
          building_id: string;
          space_id: string;
          user_id: string;
          start_time: string;
          end_time: string;
          status: string;
          reference_code: string;
          payment_amount: number | null;
          payment_proof_url: string | null;
          payment_verified_by: string | null;
          payment_verified_at: string | null;
          payment_rejected_reason: string | null;
          payment_deadline: string | null;
          cancellation_reason: string | null;
          cancelled_by: string | null;
          notes: string | null;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          building_id: string;
          space_id: string;
          user_id: string;
          start_time: string;
          end_time: string;
          status?: string;
          reference_code: string;
          payment_amount?: number | null;
          payment_proof_url?: string | null;
          payment_verified_by?: string | null;
          payment_verified_at?: string | null;
          payment_rejected_reason?: string | null;
          payment_deadline?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          notes?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          building_id?: string;
          space_id?: string;
          user_id?: string;
          start_time?: string;
          end_time?: string;
          status?: string;
          reference_code?: string;
          payment_amount?: number | null;
          payment_proof_url?: string | null;
          payment_verified_by?: string | null;
          payment_verified_at?: string | null;
          payment_rejected_reason?: string | null;
          payment_deadline?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          notes?: string | null;
          version?: number;
          updated_at?: string;
        };
      };
      announcements: {
        Row: {
          id: string;
          building_id: string;
          title: string;
          body: string;
          target: string;
          created_by: string | null;
          published_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          building_id: string;
          title: string;
          body: string;
          target?: string;
          created_by?: string | null;
          published_at?: string;
          expires_at?: string | null;
        };
        Update: {
          building_id?: string;
          title?: string;
          body?: string;
          target?: string;
          created_by?: string | null;
          published_at?: string;
          expires_at?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          data: Json | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          data?: Json | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          type?: string;
          title?: string;
          body?: string | null;
          data?: Json | null;
          read_at?: string | null;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          building_id: string | null;
          user_id: string | null;
          action: string;
          table_name: string;
          record_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          building_id?: string | null;
          user_id?: string | null;
          action: string;
          table_name: string;
          record_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          created_at?: string;
        };
        Update: {
          building_id?: string | null;
          user_id?: string | null;
          action?: string;
          table_name?: string;
          record_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
        };
      };
    };
    Functions: {
      check_space_availability: {
        Args: {
          p_space_id: string;
          p_start: string;
          p_end: string;
          p_exclude_reservation_id?: string;
        };
        Returns: boolean;
      };
      generate_reference_code: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
  };
}
